### PR TITLE
Yui integration

### PR DESCRIPTION
**Pull request by rrusso**

### CODE REVIEW

**Comment by adamzap** [comment]
Was this a mistake? What do these commits do for us?

**Comment by rrusso** [comment]
Phil said he was implementing YUI. no idea other than that.

**Comment by adamzap** [comment]
Ok...these commits are from 24 days ago though.

@philcali please weigh in.

**Comment by philcali** [comment]
These commits are incompatible with master. The branch was created at the
start of the project to kick start yui integration, if that was a desired
path.

-- Philip Cali
On Apr 19, 2012 10:36 AM, "Adam Zapletal" <
reply@reply.github.com>
wrote:

**Comment by adamzap** [comment]
I chose jQuery over YUI.

**Pull request closed without merging**
